=== Nictiz/Nictiz-GZ/YATC-shared/xsd/text-document.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="https://nictiz.nl/ns/YATC-shared/text-document" xmlns:yatcs-td="https://nictiz.nl/ns/YATC-shared/text-document" xmlns:xi="http://www.w3.org/2001/XInclude">
    <!-- ======================================================================= -->
    <!--
    Copyright Â© Nictiz

    This program is free software; you can redistribute it and/or modify it under the terms of the
    GNU Lesser General Public License as published by the Free Software Foundation; either version
    2.1 of the License, or (at your option) any later version.
    
    This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
    without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Lesser General Public License for more details.
    
    The full text of the license is available at http://www.gnu.org/copyleft/lesser.html
    -->
    <!-- ======================================================================= -->

    <xs:annotation>
        <xs:documentation>Schema for the special text documents that are used to document XML formats.</xs:documentation>
    </xs:annotation>
    <xs:include schemaLocation="../xsdmod/general.mod.xsd"/>

    <xs:import namespace="http://www.w3.org/2001/XInclude" schemaLocation="../xsdmod/xinclude.mod.xsd"/>
    <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="../xsdmod/xml.mod.xsd"/>
    <xs:element name="text-document">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="yatcs-td:ct-section">
                    <xs:attribute default="true" name="toc" type="xs:boolean">
                        <xs:annotation>
                            <xs:documentation>Whether to add a toc section upfront.</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:group name="g-titlle">
        <xs:sequence>
            <xs:element name="title" type="yatcs-td:ct-mixed-contents"/>
        </xs:sequence>
    </xs:group>
    <xs:group name="g-para">
        <xs:sequence>
            <xs:element name="para" type="yatcs-td:ct-mixed-contents"/>
        </xs:sequence>
    </xs:group>
    <xs:group name="g-block-contents">
        <xs:sequence>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="xi:include"/>
                <xs:group ref="yatcs-td:g-para"/>
                <xs:element name="codeblock">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="yatcs-td:t-non-zero-length-string">
                                <xs:attribute name="language" type="yatcs-td:t-non-zero-length-string">
                                    <xs:annotation>
                                        <xs:documentation>This will be set as the language used. Not sure whether it has any effect...</xs:documentation>
                                    </xs:annotation>
                                </xs:attribute>
                                <xs:attribute ref="xml:space"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dividerline" type="yatcs-td:ct-empy"/>
                <xs:element name="emptyline" type="yatcs-td:ct-empy"/>
                <xs:element name="markdown">
                    <xs:annotation>
                        <xs:documentation>Straight markdown text, copied verbatim.</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute ref="xml:space"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="subheading" type="yatcs-td:ct-mixed-contents"/>
                <xs:group ref="yatcs-td:g-lists"/>
                <xs:group ref="yatcs-td:g-table"/>
                <xs:group ref="yatcs-td:g-element"/>
                <xs:element ref="yatcs-td:group"/>
                <xs:element ref="yatcs-td:section"/>
                <xs:element name="include-command-help-text">
                    <xs:annotation>
                        <xs:documentation>Include a command help text as Markdown</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="yatcs-td:ct-empy">
                                <xs:attribute name="href" type="xs:anyURI" use="required"/>
                            </xs:extension>
                        </xs:complexContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="image">
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="yatcs-td:ct-empty">
                                <xs:attribute name="href" type="xs:anyURI" use="required"/>
                                <xs:attribute name="scale" type="xs:string">
                                    <xs:annotation>
                                        <xs:documentation>Any scaling accepted by CSS. For instance "25%".</xs:documentation>
                                    </xs:annotation>
                                </xs:attribute>
                            </xs:extension>
                        </xs:complexContent>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:sequence>
    </xs:group>
    <xs:group name="g-lists">
        <xs:sequence>
            <xs:choice>
                <xs:element name="unorderedlist" type="yatcs-td:ct-list"/>
                <xs:element name="orderedlist" type="yatcs-td:ct-list"/>
            </xs:choice>
        </xs:sequence>
    </xs:group>
    <xs:group name="g-table">
        <xs:sequence>
            <xs:element name="table">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="header" type="yatcs-td:ct-table-row"/>
                        <xs:element maxOccurs="unbounded" name="row" type="yatcs-td:ct-table-row"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:group>
    <xs:group name="g-element">
        <xs:sequence>
            <xs:element name="element">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="attributes">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element maxOccurs="unbounded" minOccurs="0" name="attribute">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:group ref="yatcs-td:g-para"/>
                                            </xs:sequence>
                                            <xs:attribute name="name" type="yatcs-td:t-non-zero-length-string" use="required"/>
                                            <xs:attribute name="type" type="xs:string" use="required"/>
                                            <xs:attribute default="false" name="required" type="xs:boolean"/>
                                            <xs:attribute name="default" type="xs:string"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element minOccurs="0" name="children">
                            <xs:complexType>
                                <xs:choice maxOccurs="unbounded" minOccurs="0">
                                    <xs:group ref="yatcs-td:g-child-element"/>
                                    <xs:element name="choice">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:group maxOccurs="unbounded" ref="yatcs-td:g-child-element"/>
                                            </xs:sequence>
                                            <xs:attributeGroup ref="yatcs-td:ag-occurrences"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:choice>
                            </xs:complexType>
                        </xs:element>
                        <xs:element minOccurs="0" name="additional-text" type="yatcs-td:t-non-zero-length-string"/>
                    </xs:sequence>
                    <xs:attribute name="name" type="yatcs-td:t-non-zero-length-string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:group>
    <xs:group name="g-child-element">
        <xs:sequence>
            <xs:element name="element">
                <xs:complexType>
                    <xs:sequence>
                        <xs:group ref="yatcs-td:g-para"/>
                    </xs:sequence>
                    <xs:attribute name="name" type="yatcs-td:t-non-zero-length-string" use="required"/>
                    <xs:attributeGroup ref="yatcs-td:ag-occurrences"/>
                    <xs:attribute name="pseudo-attributes">
                        <xs:annotation>
                            <xs:documentation>List of attributes that will be shown as attr="..."</xs:documentation>
                        </xs:annotation>
                        <xs:simpleType>
                            <xs:list itemType="xs:string"/>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="comment" type="yatcs-td:t-non-zero-length-string">
                        <xs:annotation>
                            <xs:documentation>Short text displayed after the element in the code listing only.</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute default="false" name="attributes-indicator" type="xs:boolean">
                        <xs:annotation>
                            <xs:documentation>Add a ... to indicate that attributes are present (but not specifically mentioned here, probably below in another section)</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute default="false" name="close" type="xs:boolean">
                        <xs:annotation>
                            <xs:documentation>Whether the element should be closed (indicating no children)</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:group>
    <xs:attributeGroup name="ag-occurrences">
        <xs:attribute default="1" name="occurrences">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:length value="1"/>
                    <xs:enumeration value="*"/>
                    <xs:enumeration value="1"/>
                    <xs:enumeration value="?"/>
                    <xs:enumeration value="+"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:attributeGroup>
    <xs:group name="g-macros">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="macro">
                <xs:annotation>
                    <xs:documentation>Definition of a (simple) macro for expansion in test</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:complexContent>
                        <xs:extension base="yatcs-td:ct-empy">
                            <xs:attribute name="name" type="xs:NCName" use="required"/>
                            <xs:attribute name="value" type="xs:string" use="required"/>
                            <xs:attribute name="default" type="xs:string">
                                <xs:annotation>
                                    <xs:documentation>If @value (caused by parameter substitutions) expands to empty, this value will be used.</xs:documentation>
                                </xs:annotation>
                            </xs:attribute>
                        </xs:extension>
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:group>
    <xs:complexType name="ct-table-row">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="entry">
                <xs:complexType>
                    <xs:sequence>
                        <xs:group ref="yatcs-td:g-para"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ct-section">
        <xs:sequence>
            <xs:group ref="yatcs-td:g-macros"/>
            <xs:group ref="yatcs-td:g-titlle"/>
            <xs:group ref="yatcs-td:g-block-contents"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType mixed="true" name="ct-mixed-contents">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="code" type="yatcs-td:t-non-zero-length-string"/>
            <xs:element name="emph">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="yatcs-td:t-non-zero-length-string">
                            <xs:attribute default="false" name="bold" type="xs:boolean"/>
                            <xs:attribute default="true" name="italic" type="xs:boolean"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="link">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="href" type="xs:anyURI" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="anchor">
                <xs:complexType>
                    <xs:attribute name="name" type="yatcs-td:t-identifier" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="br" type="yatcs-td:ct-empy"/>
            <xs:element name="elm" type="yatcs-td:t-non-zero-length-string"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="ct-list">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="entry">
                <xs:complexType>
                    <xs:sequence>
                        <xs:group ref="yatcs-td:g-para"/>
                        <xs:group minOccurs="0" ref="yatcs-td:g-lists"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ct-empy"/>
    <xs:element name="section" type="yatcs-td:ct-section">
        <xs:annotation>
            <xs:documentation>A section in the document</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="group">
        <xs:annotation>
            <xs:documentation>A group of block content. Use this for including pieces of text.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:group ref="yatcs-td:g-block-contents"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Nictiz/Nictiz-GZ/YATC-shared/srcmod/standard-distributions-element.mod.xml
<section xmlns="https://nictiz.nl/ns/YATC-shared/text-document" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://nictiz.nl/ns/YATC-shared/text-document ../xsd/text-document.xsd" xmlns:xi="http://www.w3.org/2001/XInclude">

    <!-- ======================================================================= -->
    <!-- 
        General text about the <distributions> element in application data files.
        
        This element is defined in ../xsdmod/application-data-file.mod.xsd
    -->
    <!-- ======================================================================= -->
    <!--
        Copyright Â© Nictiz
        
        This program is free software; you can redistribute it and/or modify it under the terms of the
        GNU Lesser General Public License as published by the Free Software Foundation; either version
        2.1 of the License, or (at your option) any later version.
        
        This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
        without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
        See the GNU Lesser General Public License for more details.
        
        The full text of the license is available at http://www.gnu.org/copyleft/lesser.html
    -->
    <!-- ======================================================================= -->

    <title><anchor name="distributions"/>The <elm>distributions</elm> element</title>

    <para>The <elm>distributions</elm> defines one or more distributions. For a description of distributions in general and the details of the <elm>distributions</elm> element, see <link href="../../../YATC-shared/doc/distributions.md">here</link>.</para>

</section>

=== Nictiz/Nictiz-GZ/YATC-internal/fhir-2-ada/doc/src/commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<text-document xmlns="https://nictiz.nl/ns/YATC-shared/text-document" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://nictiz.nl/ns/YATC-shared/text-document ../../../../YATC-shared/xsd/text-document.xsd" xmlns:xi="http://www.w3.org/2001/XInclude">
    <!-- ======================================================================= -->
    <!-- 
        Description of the commands for this component.
    -->
    <!-- ======================================================================= -->
    <!--
        Copyright Â© Nictiz
        
        This program is free software; you can redistribute it and/or modify it under the terms of the
        GNU Lesser General Public License as published by the Free Software Foundation; either version
        2.1 of the License, or (at your option) any later version.
        
        This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
        without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
        See the GNU Lesser General Public License for more details.
        
        The full text of the license is available at http://www.gnu.org/copyleft/lesser.html
    -->
    <!-- ======================================================================= -->

    <macro name="DATAFILENAME" value="{$yatcComponentName}-data.xml"/>
    <macro name="PARBASESTORAGE" value="ada2fhirBaseStorageDirectory"/>
    <macro name="PARDATADOCUMENT" value="ada2fhirDataDocument"/>

    <title><code>{$yatcRepositoryName}/{$yatcComponentName}</code> available commands</title>

    <xi:include href="../../../../YATC-shared/srcmod/commands-common-opening.xml"/>

    <section>
        <macro name="COMMAND" value="{$yatcComponentName}"/>

        <title>Command: <code>yatc $COMMAND</code></title>

        <include-command-help-text href="../../bin/$COMMAND.bat"/>

        <emptyline/>
        <para>Command line examples:</para>
        <unorderedlist>
            <entry>
                <para><code>yatc $COMMAND -list</code><br/>Lists the available application/version combinations.</para>
            </entry>
            <entry>
                <para><code>yatc $COMMAND -process mp 9.0.7</code><br/>Performs the FHIR to ADA conversion(s) for application <code>mp</code>, version <code>9.0.7</code>.</para>
            </entry>
            <entry>
                <para><code>yatc $COMMAND mp 9.0.7</code><br/>Same as above (the <code>-process</code> flag is optional).</para>
            </entry>
            <entry>
                <para><code>yatc $COMMAND -process #all #all</code><br/>Performs the FHIR 2 ADA conversion(s) for all applications/versions known.</para>
            </entry>
        </unorderedlist>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <section>
            <title>YATC parameter usage</title>

            <xi:include href="../../../../YATC-shared/srcmod/commands-base-parameters-usage.xml"/>
        </section>

    </section>

    <!-- ======================================================================= -->

    <section>
        <macro name="COMMAND" value="compare-{$yatcComponentName}"/>

        <title>Command: <code>yatc $COMMAND</code></title>

        <include-command-help-text href="../../bin/$COMMAND.bat"/>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <section>
            <title>How to use</title>

            <xi:include href="../../../../YATC-shared/srcmod/commands-compare-description.xml"/>
        </section>

    </section>

</text-document>

=== Nictiz/Nictiz-GZ/doc/src/parameters-format-reference.xml
<?xml version="1.0" encoding="UTF-8"?>
<text-document xmlns="https://nictiz.nl/ns/YATC-shared/text-document" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://nictiz.nl/ns/YATC-shared/text-document ../../xsd/text-document.xsd">
    <!-- ======================================================================= -->
    <!-- 
        Documentation for the parameters XML format. 
    -->
    <!-- ======================================================================= -->
    <!--
        Copyright Â© Nictiz
        
        This program is free software; you can redistribute it and/or modify it under the terms of the
        GNU Lesser General Public License as published by the Free Software Foundation; either version
        2.1 of the License, or (at your option) any later version.
        
        This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
        without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
        See the GNU Lesser General Public License for more details.
        
        The full text of the license is available at http://www.gnu.org/copyleft/lesser.html
    -->
    <!-- ======================================================================= -->

    <title>Parameters XML format reference</title>

    <para>Parameters are defined using XML documents in the parameters format.</para>
    <unorderedlist>
        <entry>
            <para>The schema for these documents is in <code>YATC-shared/xsd/parameters.xsd</code>.</para>
        </entry>
        <entry>
            <para>Documentation of the parameters system in general can be found <link href="parameters-system.md">here</link>.</para>
        </entry>
    </unorderedlist>

    <para>The parameters format, as described here, has a dual purpose:</para>
    <unorderedlist>
        <entry>
            <para>It is meant for the parameters XML documents that define the value(s) for the parameters. Most of these are in <code>data/parameters.xml</code> documents.</para>
        </entry>
        <entry>
            <para>Some attributes and elements will be filled in by the system that gathers everything and creates the parameters XML document that applications can work with. You can see this in action using the <code>get-parameters-xml</code> command.</para>
        </entry>
    </unorderedlist>

    <!-- ======================================================================= -->

    <section>
        <title>Root <elm>parameters</elm> element</title>

        <element name="parameters">
            <attributes>
                <attribute name="caller-static-base-uri" type="xs:anyURI">
                    <para>(Filled in by the parameter gathering process)<br/>The base URI of the caller when gathering the parameters. This can be interesting since the set of parameters depends on this location.</para>
                </attribute>
            </attributes>
            <children>
                <element name="sources" occurrences="?">
                    <para>(Filled in by the parameter gathering process.)<br/>A list of source document URIs for the parameters in the document.</para>
                </element>
                <element name="parameter" occurrences="*">
                    <para>Definition of a single parameter.</para>
                </element>
            </children>
        </element>
    </section>

    <!-- ======================================================================= -->

    <section>
        <title><elm>parameter</elm> element</title>

        <para>A <elm>parameter</elm> element defines the value(s) for a single parameter.</para>

        <element name="parameter">
            <attributes>
                <attribute name="name" type="xs:NCName" required="true">
                    <para>The name of the parameter.</para>
                </attribute>
                <attribute name="source-idref" type="xs:NCName">
                    <para>(Filled in by the parameter gathering process.)<br/>The identifier of the <code>/*/sources/source</code> element that is the source for this parameter value.<br/>Remark: Some parameters do not have a source because they're created by the parameter gathering process (like <code>yatcBaseDirectory</code>. In that case this attribute will be absent</para>
                </attribute>
            </attributes>
            <children>
                <element name="value" occurrences="*">
                    <para>Contains the (string) value of the parameter.</para>
                </element>
            </children>
        </element>
    </section>

    <!-- ======================================================================= -->

    <section>
        <title><elm>sources</elm> element</title>

        <para>The <elm>sources</elm> element is a list of source documents for the value(s) of the parameters. All source documents have an identifier. Parameters reference these identifiers with their <code>@source-idref</code> attribute. It is filled in/created by the parameter gathering process.</para>
        
        <element name="sources">
           <children>
               <element name="source" occurrences="*">
                   <para>A single source document.</para>
               </element>
           </children>
        </element>
        
        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
        
        <section>
            <title><elm>source</elm> element</title>
            
            <element name="source">
                <attributes>
                    <attribute name="id" type="xs:NCName" required="true">
                        <para>The identifier as used by <elm>parameter</elm> elements to reference this source</para>
                    </attribute>
                </attributes>
                <additional-text>The URI of the source document.</additional-text>
            </element>
            
        </section>
    </section>

</text-document>
