=== Nictiz/Nictiz-GZ/YATC-shared/xsd/text-document.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="https://nictiz.nl/ns/YATC-shared/text-document" xmlns:yatcs-td="https://nictiz.nl/ns/YATC-shared/text-document" xmlns:xi="http://www.w3.org/2001/XInclude">
    <!-- ======================================================================= -->
    <!--
    Copyright Â© Nictiz

    This program is free software; you can redistribute it and/or modify it under the terms of the
    GNU Lesser General Public License as published by the Free Software Foundation; either version
    2.1 of the License, or (at your option) any later version.
    
    This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
    without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Lesser General Public License for more details.
    
    The full text of the license is available at http://www.gnu.org/copyleft/lesser.html
    -->
    <!-- ======================================================================= -->

    <xs:annotation>
        <xs:documentation>Schema for the special text documents that are used to document XML formats.</xs:documentation>
    </xs:annotation>
    <xs:include schemaLocation="../xsdmod/general.mod.xsd"/>

    <xs:import namespace="http://www.w3.org/2001/XInclude" schemaLocation="../xsdmod/xinclude.mod.xsd"/>
    <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="../xsdmod/xml.mod.xsd"/>
    <xs:element name="text-document">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="yatcs-td:ct-section">
                    <xs:attribute default="true" name="toc" type="xs:boolean">
                        <xs:annotation>
                            <xs:documentation>Whether to add a toc section upfront.</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:group name="g-titlle">
        <xs:sequence>
            <xs:element name="title" type="yatcs-td:ct-mixed-contents"/>
        </xs:sequence>
    </xs:group>
    <xs:group name="g-para">
        <xs:sequence>
            <xs:element name="para" type="yatcs-td:ct-mixed-contents"/>
        </xs:sequence>
    </xs:group>
    <xs:group name="g-block-contents">
        <xs:sequence>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="xi:include"/>
                <xs:group ref="yatcs-td:g-para"/>
                <xs:element name="codeblock">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="yatcs-td:t-non-zero-length-string">
                                <xs:attribute name="language" type="yatcs-td:t-non-zero-length-string">
                                    <xs:annotation>
                                        <xs:documentation>This will be set as the language used. Not sure whether it has any effect...</xs:documentation>
                                    </xs:annotation>
                                </xs:attribute>
                                <xs:attribute ref="xml:space"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dividerline" type="yatcs-td:ct-empy"/>
                <xs:element name="emptyline" type="yatcs-td:ct-empy"/>
                <xs:element name="markdown">
                    <xs:annotation>
                        <xs:documentation>Straight markdown text, copied verbatim.</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute ref="xml:space"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="subheading" type="yatcs-td:ct-mixed-contents"/>
                <xs:group ref="yatcs-td:g-lists"/>
                <xs:group ref="yatcs-td:g-table"/>
                <xs:group ref="yatcs-td:g-element"/>
                <xs:element ref="yatcs-td:group"/>
                <xs:element ref="yatcs-td:section"/>
                <xs:element name="include-command-help-text">
                    <xs:annotation>
                        <xs:documentation>Include a command help text as Markdown</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="yatcs-td:ct-empy">
                                <xs:attribute name="href" type="xs:anyURI" use="required"/>
                            </xs:extension>
                        </xs:complexContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="image">
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="yatcs-td:ct-empty">
                                <xs:attribute name="href" type="xs:anyURI" use="required"/>
                                <xs:attribute name="scale" type="xs:string">
                                    <xs:annotation>
                                        <xs:documentation>Any scaling accepted by CSS. For instance "25%".</xs:documentation>
                                    </xs:annotation>
                                </xs:attribute>
                            </xs:extension>
                        </xs:complexContent>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:sequence>
    </xs:group>
    <xs:group name="g-lists">
        <xs:sequence>
            <xs:choice>
                <xs:element name="unorderedlist" type="yatcs-td:ct-list"/>
                <xs:element name="orderedlist" type="yatcs-td:ct-list"/>
            </xs:choice>
        </xs:sequence>
    </xs:group>
    <xs:group name="g-table">
        <xs:sequence>
            <xs:element name="table">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="header" type="yatcs-td:ct-table-row"/>
                        <xs:element maxOccurs="unbounded" name="row" type="yatcs-td:ct-table-row"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:group>
    <xs:group name="g-element">
        <xs:sequence>
            <xs:element name="element">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="attributes">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element maxOccurs="unbounded" minOccurs="0" name="attribute">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:group ref="yatcs-td:g-para"/>
                                            </xs:sequence>
                                            <xs:attribute name="name" type="yatcs-td:t-non-zero-length-string" use="required"/>
                                            <xs:attribute name="type" type="xs:string" use="required"/>
                                            <xs:attribute default="false" name="required" type="xs:boolean"/>
                                            <xs:attribute name="default" type="xs:string"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element minOccurs="0" name="children">
                            <xs:complexType>
                                <xs:choice maxOccurs="unbounded" minOccurs="0">
                                    <xs:group ref="yatcs-td:g-child-element"/>
                                    <xs:element name="choice">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:group maxOccurs="unbounded" ref="yatcs-td:g-child-element"/>
                                            </xs:sequence>
                                            <xs:attributeGroup ref="yatcs-td:ag-occurrences"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:choice>
                            </xs:complexType>
                        </xs:element>
                        <xs:element minOccurs="0" name="additional-text" type="yatcs-td:t-non-zero-length-string"/>
                    </xs:sequence>
                    <xs:attribute name="name" type="yatcs-td:t-non-zero-length-string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:group>
    <xs:group name="g-child-element">
        <xs:sequence>
            <xs:element name="element">
                <xs:complexType>
                    <xs:sequence>
                        <xs:group ref="yatcs-td:g-para"/>
                    </xs:sequence>
                    <xs:attribute name="name" type="yatcs-td:t-non-zero-length-string" use="required"/>
                    <xs:attributeGroup ref="yatcs-td:ag-occurrences"/>
                    <xs:attribute name="pseudo-attributes">
                        <xs:annotation>
                            <xs:documentation>List of attributes that will be shown as attr="..."</xs:documentation>
                        </xs:annotation>
                        <xs:simpleType>
                            <xs:list itemType="xs:string"/>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="comment" type="yatcs-td:t-non-zero-length-string">
                        <xs:annotation>
                            <xs:documentation>Short text displayed after the element in the code listing only.</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute default="false" name="attributes-indicator" type="xs:boolean">
                        <xs:annotation>
                            <xs:documentation>Add a ... to indicate that attributes are present (but not specifically mentioned here, probably below in another section)</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute default="false" name="close" type="xs:boolean">
                        <xs:annotation>
                            <xs:documentation>Whether the element should be closed (indicating no children)</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:group>
    <xs:attributeGroup name="ag-occurrences">
        <xs:attribute default="1" name="occurrences">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:length value="1"/>
                    <xs:enumeration value="*"/>
                    <xs:enumeration value="1"/>
                    <xs:enumeration value="?"/>
                    <xs:enumeration value="+"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:attributeGroup>
    <xs:group name="g-macros">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="macro">
                <xs:annotation>
                    <xs:documentation>Definition of a (simple) macro for expansion in test</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:complexContent>
                        <xs:extension base="yatcs-td:ct-empy">
                            <xs:attribute name="name" type="xs:NCName" use="required"/>
                            <xs:attribute name="value" type="xs:string" use="required"/>
                            <xs:attribute name="default" type="xs:string">
                                <xs:annotation>
                                    <xs:documentation>If @value (caused by parameter substitutions) expands to empty, this value will be used.</xs:documentation>
                                </xs:annotation>
                            </xs:attribute>
                        </xs:extension>
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:group>
    <xs:complexType name="ct-table-row">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="entry">
                <xs:complexType>
                    <xs:sequence>
                        <xs:group ref="yatcs-td:g-para"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ct-section">
        <xs:sequence>
            <xs:group ref="yatcs-td:g-macros"/>
            <xs:group ref="yatcs-td:g-titlle"/>
            <xs:group ref="yatcs-td:g-block-contents"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType mixed="true" name="ct-mixed-contents">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="code" type="yatcs-td:t-non-zero-length-string"/>
            <xs:element name="emph">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="yatcs-td:t-non-zero-length-string">
                            <xs:attribute default="false" name="bold" type="xs:boolean"/>
                            <xs:attribute default="true" name="italic" type="xs:boolean"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="link">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="href" type="xs:anyURI" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="anchor">
                <xs:complexType>
                    <xs:attribute name="name" type="yatcs-td:t-identifier" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="br" type="yatcs-td:ct-empy"/>
            <xs:element name="elm" type="yatcs-td:t-non-zero-length-string"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="ct-list">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="entry">
                <xs:complexType>
                    <xs:sequence>
                        <xs:group ref="yatcs-td:g-para"/>
                        <xs:group minOccurs="0" ref="yatcs-td:g-lists"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ct-empy"/>
    <xs:element name="section" type="yatcs-td:ct-section">
        <xs:annotation>
            <xs:documentation>A section in the document</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="group">
        <xs:annotation>
            <xs:documentation>A group of block content. Use this for including pieces of text.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:group ref="yatcs-td:g-block-contents"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Nictiz/Nictiz-GZ/distribute/doc/src/component-documentation.xml
<?xml version="1.0" encoding="UTF-8"?>
<text-document xmlns="https://nictiz.nl/ns/YATC-shared/text-document" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://nictiz.nl/ns/YATC-shared/text-document ../../../../YATC-shared/xsd/text-document.xsd" xmlns:xi="http://www.w3.org/2001/XInclude">
    <!-- ======================================================================= -->
    <!-- 
        Documentation for the distributions system
    -->
    <!-- ======================================================================= -->
    <!--
        Copyright © Nictiz
        
        This program is free software; you can redistribute it and/or modify it under the terms of the
        GNU Lesser General Public License as published by the Free Software Foundation; either version
        2.1 of the License, or (at your option) any later version.
        
        This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
        without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
        See the GNU Lesser General Public License for more details.
        
        The full text of the license is available at http://www.gnu.org/copyleft/lesser.html
    -->
    <!-- ======================================================================= -->

    <title><anchor name="distributions-description"/>Distributions</title>

    <section>
        <title>Overview</title>

        <para>The <code>YATC-internal/distribute</code> component allows you to merge results and/or scripts into what is called a <emph>distribution</emph>.</para>

        <para>A distribution is a collection of directory/file copies to some location. The idea is that a distribution gathers all necessary files for some additional  application/purpose/user/customer. For instance, the stylesheets an external customer needs, or parts of the output documents produced. </para>

        <para>A distribution has the following features:</para>
        <unorderedlist>
            <entry>
                <para>A distribution has a <emph>name</emph>, by which it can be identified/started.</para>
            </entry>
            <entry>
                <para>A distribution consists of:</para>
                <unorderedlist>
                    <entry>
                        <para>Directory copies. You can filter the documents copied by name patterns. The target directory may have a different name than the source.</para>
                    </entry>
                    <entry>
                        <para>Single file copies. The target file may have a different name than the source.</para>
                    </entry>
                    <entry>
                        <para>Copies of additional text documents, for instance readme files or license texts. Within these files, simple macro substitutions (see <link href="data-format-reference.md#distribution-macros">distribution macros</link>) can be done, for instance to insert dates or version numbers. You can also <emph>combine</emph> multiple text files into one.</para>
                    </entry>
                    <entry>
                        <para>Flattened sets of XSLT stylesheets, XML Schemas or Schematron Schemas. Flattening means that these documents are copied first. Subsequently, all files included/imported (recursively) are copied as well, into a single sub-directory. All include/import elements are adapted to the new, flattened, layout.</para>
                    </entry>
                </unorderedlist>
            </entry>
            <entry>
                <para>The name definitions of all directories and filenames can contain simple macros (see <link href="data-format-reference.md#distribution-macros">distribution macros</link>), so you can, for instance, create a distribution directory with the date and/or time in its name.</para>
            </entry>
            <entry>
                <para>If needed, the result of the distribution can be gathered in a zip file.</para>
            </entry>
            <entry>
                <para>When creating a distribution, you have the option to provide a so-called <emph>distribution-version</emph>. This is a string that distinguishes this specific distribution from others, such as <code>3.1</code> or <code>0.4beta</code>. It is not necessary to do this, as the date and time of creation may be sufficient for identification. However, if you choose to provide a distribution-version, you can utilize it in macro substitutions for target directory/file names and additional text documents.</para>
            </entry>
        </unorderedlist>

    </section>
  
    <!-- ======================================================================= -->

    <section>
        <title>Examples</title>

        <section>
            <title>Distributing XSLT stylesheets with a readme</title>

            <para>Let's assume that the following distribution is defined:</para>

            <codeblock><![CDATA[<distribute-data>
        
    <distribution name="dist1" target-directory="TMP-$DISTRIBUTIONVERSION-$DATECOMPACT"  
            base-dir-in-zip="false" 
            href-zip="../ZIP-$DISTRIBUTIONVERSION-$DATECOMPACT.zip" distribution-version-required="true" 
            allow-overwrite="false" keep-files="false">
        
        <flatten-stylesheets source-directory="ada-2-fhir/env/ketenzorg/3.0.2/beschikbaarstellen/payload/" 
                target-directory="stylesheets"/>
        
        <combine-additional-text-documents href-target="README.txt" 
                separator="$NL$NL*******************************************************$NL$NL">
            <text-document href-source="ada-2-fhir/env/ketenzorg/3.0.2/beschikbaarstellen/README-1.txt"/>
            <text-document href-source="ada-2-fhir/env/ketenzorg/3.0.2/beschikbaarstellen/README-2.txt"/>
        </combine-additional-text-documents>
        
    </distribution>

</distribute-data>]]></codeblock>
        </section>

        <para>Assume we call it on November 14th 2023, using the command: <code>yatc distribute dist1 -version:1.16.7</code>.</para>

        <para>What it will do is:</para>
        <unorderedlist>
            
            <entry>
                <para>The distribution named <code>test1</code> writes its results to a subdirectory of the main distributions directory, using some macros.</para>
                <unorderedlist>
                    <entry>
                        <para>Writes its results to a subdirectory of the main distributions directory using some macros. In the example this will become <code>TMP-1.16.7-20231114</code>.</para>
                    </entry>
                    <entry>
                        <para>Setting <code>@distribution-version-required</code> to <code>true</code> means that you <emph>must</emph> specify the <code>-version:…</code> flag on the command line when creating this distribution. It cannot run without a specific distribution version set.</para>
                    </entry>
                    <entry>
                        <para>Since the <code>@allow-overwrite</code> is set to <code>false</code>, neither the target directory nor the zip file must exist before the distribution's actions takes place.</para>
                    </entry>
                    <entry>
                        <para>The <code>@href-zip</code> attribute defines the name of the zip file that contains the distribution results. The name of this zip file will become <code>ZIP-1.16.7-20231114.zip</code> and it will be stored in the main distribution directory.<br/>Setting <code>@base-dir-in-zip</code> to <code>false</code> defines that we don't want the name of the temporary directory where we write the distribution to (<code>TMP-1.16.7-20231114</code>) to be part of the zip's contents. Only the files/sub-directories <emph>in</emph> that directory become part of the zip file.</para>
                    </entry>
                    <entry>
                        <para>Since <code>@keep-files</code> is set to <code>false</code>, the temporary distribution directory (<code>TMP-1.16.7-20231114</code>) will be deleted after the zip file is created.</para>
                    </entry>
                </unorderedlist>
            </entry>
            <entry>
                <para>The first part of the distribution is a flattened collection of stylesheets from the code base of <code>YATC-internal/ada-2-fhir</code>. These files will be placed in a sub-directory <code>stylesheets</code>. There will also be a sub-directory <code>stylesheets/include</code>, where all the includes/imports live.</para>
            </entry>
            <entry>
                <para>Finally a <code>README.txt</code> file is created, combining two separate (imaginary) readme files. A line with stars is used as separator.</para>
            </entry>
        </unorderedlist>

        <para>The result of this distribution will be a zip file <code>ZIP-1.16.7-20231114.zip</code>. At root level it contains a sub-directory <code>stylesheets</code> and a <code>README.txt</code> document.</para>

    </section>

</text-document>
