=== Nictiz/Nictiz-GZ/xsd/command-help-text.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="https://nictiz.nl/ns/YATC-shared/command-help-text" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:yatcs-cht="https://nictiz.nl/ns/YATC-shared/command-help-text">
    <!-- ======================================================================= -->
    <!--
    Copyright Â© Nictiz

    This program is free software; you can redistribute it and/or modify it under the terms of the
    GNU Lesser General Public License as published by the Free Software Foundation; either version
    2.1 of the License, or (at your option) any later version.
    
    This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
    without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Lesser General Public License for more details.
    
    The full text of the license is available at http://www.gnu.org/copyleft/lesser.html
    -->
    <!-- ======================================================================= -->

    <xs:annotation>
        <xs:documentation>Schema for the special text documents that are used to document XML formats.</xs:documentation>
    </xs:annotation>
    <xs:include schemaLocation="../xsdmod/general.mod.xsd"/>

    <xs:import namespace="http://www.w3.org/2001/XInclude" schemaLocation="../xsdmod/xinclude.mod.xsd"/>
    <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="../xsdmod/xml.mod.xsd"/>
    <xs:element name="command-help-text">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="description" type="xs:string"/>
                <xs:choice minOccurs="0">
                    <xs:element ref="yatcs-cht:command-line-options"/>
                    <xs:element ref="xi:include"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="command" type="yatcs-cht:t-non-zero-length-string">
                <xs:annotation>
                    <xs:documentation>The name of the command. Use this to override the command name that is inferred from the static base URI.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="ct-flag-argument">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="yatcs-cht:t-non-zero-length-string" use="required">
                    <xs:annotation>
                        <xs:documentation>The name of the argument or flag. Do not use a - in front of a flag.</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute default="false" name="optional" type="xs:boolean"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:element name="command-line-options">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element ref="yatcs-cht:command-line-option"/>
                <xs:element ref="xi:include"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="command-line-option">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="flag">
                        <xs:complexType>
                            <xs:complexContent>
                                <xs:extension base="yatcs-cht:ct-flag-argument">
                                    <xs:attribute name="argument" type="yatcs-cht:t-non-zero-length-string">
                                        <xs:annotation>
                                            <xs:documentation>A description for the argument of the flag</xs:documentation>
                                        </xs:annotation>
                                    </xs:attribute>
                                </xs:extension>
                            </xs:complexContent>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="argument" type="yatcs-cht:ct-flag-argument"/>
                </xs:choice>
                <xs:element name="description" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Nictiz/Nictiz-GZ/general-engine/chtmod/general-processing-standard-command-line-options.xml
<?xml version="1.0" encoding="UTF-8"?>
<command-line-options xmlns="https://nictiz.nl/ns/YATC-shared/command-help-text" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://nictiz.nl/ns/YATC-shared/command-help-text ../../xsd/command-help-text.xsd" xmlns:xi="http://www.w3.org/2001/XInclude">
    <!-- ======================================================================= -->
    <!-- 
        Standard command line options for the general engine command line
    -->
    <!-- ======================================================================= -->
    <!--
        Copyright Â© Nictiz
        
        This program is free software; you can redistribute it and/or modify it under the terms of the
        GNU Lesser General Public License as published by the Free Software Foundation; either version
        2.1 of the License, or (at your option) any later version.
        
        This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
        without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
        See the GNU Lesser General Public License for more details.
        
        The full text of the license is available at http://www.gnu.org/copyleft/lesser.html
    -->
    <!-- ======================================================================= -->

    <xi:include href="../../chtmod/help-command-line-option.xml"/>
    <xi:include href="../../chtmod/list-command-line-option.xml"/>
    <command-line-option>
        <flag name="actionlist" optional="false"/>
        <argument name="application" optional="true"/>
        <argument name="version" optional="true"/>
        <description>Get a list of available actions (if any) for the given application/version combinations. To get the actions for all applications/versions available, use either `#all` or `%all` for the argument(s) or leave the argument(s) empty.</description>
    </command-line-option>
    <command-line-option>
        <flag name="process" optional="true"/>
        <flag name="nosetup" optional="true">Do not process the setup elements.</flag>
        <flag name="setup" optional="true">Always process the setup elements, even when an action turns setup off. Takes precedence over -nosetup.</flag>
        <flag name="action" optional="true" argument="...">Perform the action(s) specified. Separate multiple actions with a `+` (for instance `-action:ac1+ac2`). If not specified, the action flagged as default is processed (if any).</flag>
        <flag name="testmode" optional="true">Run in test mode. This will reduce the set of input documents for build and validate steps to only one.</flag>
        <argument name="application"/>
        <argument name="version"/>

        <description>Process the available application/version combinations. To process all applications/versions available, use either `#all` or `%all` for the argument(s).</description>

    </command-line-option>

</command-line-options>
